### ISSUE TITLE
Unable to boot

### ISSUE THREAD

**Issue by dben41** [IntuitDeveloper/OAuth2-Java#1]
I have Java 1.8.0_181, as well as the other pre-reqs. I get the following error when trying to run `gradlew.bat bootRun`:

```
\OAuth2-Java>gradlew.bat bootRun
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

FAILURE: Build failed with an exception.

* What went wrong:
org.slf4j.helpers.NOPLoggerFactory cannot be cast to org.gradle.logging.internal.slf4j.OutputEventListenerBackedLoggerContext
```

Are there some additional pre-reqs that are needed?

**Comment by diana-derose** [comment]
@dben41  - Can you check if you have multiple SLF4J bindings in your class path?
Also, try one of the following samples to see if the error goes away, these samples show similar usecase using Intuit SDK.
https://github.com/IntuitDeveloper/OAuth2-JavaWithSDK
https://github.com/IntuitDeveloper/HelloWorld-Java
